<footer>
    <div class="all-width">
        <div class="foot-wrap">
            <div class="foot-logo">
                <img src="images/foot-logo.png" alt="">
            </div>
            <ul class="foot-list">
                <li class="flex"><i class="fa-solid fa-location-dot"></i>406臺中市北屯區北屯路360號8樓之2</li>
                <li class="flex"><i class="fa-solid fa-phone"></i>04-22464888</li>
                <li class="flex"><i class="fa-solid fa-fax"></i>04-22434663</li>
                <li class="flex"><i class="fa-solid fa-envelope"></i>atta@atta.org.tw</li>
            </ul>
            <div class="foot-link">
                <a href="about.asp" title="公會組織">公會組織</a>
                <a href="member.asp" title="會員名冊">會員名冊</a>
                <a href="course.asp" title="課程與活動">課程與活動</a>
                <a href="news.asp" title="最新消息">最新消息</a>
                <a href="download.asp" title="下載專區">下載專區</a>
                <a href="link.asp" title="網站連結">網站連結</a>
                <a href="contact.asp" title="聯絡我們">聯絡我們</a>
            </div>
        </div>
        <div class="foot-btm">
            <span>©2024 The Association Of Taichung Travel Agency All Rights Reserved.</span><span>Design by 一化<a href="https://www.webdesigns.com.tw">網頁設計</a></span>
        </div>
    </div>
</footer>
<div class="side-link flex">
    <a href="" class="side-link__item side-link__item--LINE flex"><!-- Generated by IcoMoon.io -->
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>line2</title>
        <path fill="#ffffff" d="M25.82 13.151c0.465 0 0.84 0.38 0.84 0.841 0 0.46-0.375 0.84-0.84 0.84h-2.34v1.5h2.34c0.465 0 0.84 0.377 0.84 0.84 0 0.459-0.375 0.839-0.84 0.839h-3.181c-0.46 0-0.836-0.38-0.836-0.839v-6.361c0-0.46 0.376-0.84 0.84-0.84h3.181c0.461 0 0.836 0.38 0.836 0.84 0 0.465-0.375 0.84-0.84 0.84h-2.34v1.5zM20.68 17.172c0 0.36-0.232 0.68-0.576 0.795-0.085 0.028-0.177 0.041-0.265 0.041-0.281 0-0.521-0.12-0.68-0.333l-3.257-4.423v3.92c0 0.459-0.372 0.839-0.841 0.839-0.461 0-0.835-0.38-0.835-0.839v-6.361c0-0.36 0.231-0.68 0.573-0.793 0.080-0.031 0.181-0.044 0.259-0.044 0.26 0 0.5 0.139 0.66 0.339l3.283 4.44v-3.941c0-0.46 0.376-0.84 0.84-0.84 0.46 0 0.84 0.38 0.84 0.84zM13.025 17.172c0 0.459-0.376 0.839-0.841 0.839-0.46 0-0.836-0.38-0.836-0.839v-6.361c0-0.46 0.376-0.84 0.84-0.84 0.461 0 0.837 0.38 0.837 0.84zM9.737 18.011h-3.181c-0.46 0-0.84-0.38-0.84-0.839v-6.361c0-0.46 0.38-0.84 0.84-0.84 0.464 0 0.84 0.38 0.84 0.84v5.521h2.341c0.464 0 0.839 0.377 0.839 0.84 0 0.459-0.376 0.839-0.839 0.839zM32 13.752c0-7.161-7.18-12.989-16-12.989s-16 5.828-16 12.989c0 6.415 5.693 11.789 13.38 12.811 0.521 0.109 1.231 0.344 1.411 0.787 0.16 0.401 0.105 1.021 0.051 1.44l-0.219 1.36c-0.060 0.401-0.32 1.581 1.399 0.86 1.721-0.719 9.221-5.437 12.581-9.3 2.299-2.519 3.397-5.099 3.397-7.957z"></path>
        </svg>
        </a>
    <a href="" class="side-link__item side-link__item--FB flex"><!-- Generated by IcoMoon.io -->
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>facebook</title>
        <path fill="#ffffff" d="M16 0c-8.838 0-16 7.162-16 16 0 7.988 5.85 14.606 13.5 15.806v-11.181h-4.063v-4.625h4.063v-3.525c0-4.009 2.387-6.225 6.044-6.225 1.75 0 3.581 0.313 3.581 0.313v3.938h-2.019c-1.988 0-2.606 1.234-2.606 2.5v3h4.438l-0.709 4.625h-3.728v11.181c7.65-1.2 13.5-7.819 13.5-15.806 0-8.838-7.163-16-16-16z"></path>
        </svg>
        </a>
</div>
<a href="javascript:;" class="scroll-top flex"><span><i class="fa-solid fa-angle-up"></i><br>TOP</span></a>